platform :ios, '8.0'
xcodeproj 'TenByTen/TenByTen.xcodeproj'
pod 'AFNetworking'
pod 'AFNetworking2-RACExtensions'
pod 'ReactiveCocoa'
pod 'MMProgressHUD'
target :TenByTenTests, :exclusive => true do
   pod 'Kiwi'
end

